server:
  port: 8081
spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Ciao"
  default-value: "Mondo"